### ISSUE TITLE
Review 09.03.2021

### ISSUE THREAD

**Issue by bitvalser** [Uladzislau-Rahinia/Innowise-Practice-Level-1#1]
Общие папки для компонентов, сервисов и тд лучше вынести в папку core

Для чего нужен RedirctWrapper? Ты просто оборачиваешь один однострочный компонент, в нём нет никакого смысла, в него не вынесена какая-либо общая логика, если тебе нужно сделать перенаправление после асинхронного действия, то делай программную навигацию, смотри useHistory 

RegisterUser, LoginUser и тд - названия методов с маленькой буквы

Что isSuccessful? используй try/catch и throw для перехвата ошибок

Eslint не настроен, куча ошибок с ним, так заранее не настроил есть много сомнительных вещей таких как инлайн useCallback, попробуй этот конфиг, поставь нужные плагины если их нет, сделай autofix линтером, но много ошибок которые линтер сам не пофиксит, исправить нужно все
`module.exports = {
  extends: ['airbnb', 'plugin:jest/recommended', 'plugin:react-hooks/recommended'],
  plugins: ['react', 'prettier'],
  rules: {
    'linebreak-style': 0,
    'react/jsx-filename-extension': [1, { extensions: ['.js', '.jsx'] }],
  },
};
`
Если есть вопрос по конфигу и ошибкам линтера пиши или сюда или мне в скайп, понимаю что некоторые ошибки могут взывать вопросы. (Но алиасы для линтера сам настроишь, там не сложно)

Ещё раз повторю перечитай как использовать useCallback, так же инлайн useCallback не используется, также useCallback не во всех случаях используется

Какой смысл выносить в общий компонент TextInput если он всего-лишь обёрнут в styled и никакой общей логики нет

Компоненты которые ориентированные только на одну страницу и нигде более использовать не будут лучше всего не выносить в общую папку components, а добавить новую папку для компонента components

Не используй циклы for, while, используй методы массива (исключение for..in, for..of)

dayConfig, monthConfig - это же обычный массив, так и пиши ['Sun', 'Mon'...

В styled есть способ задать глобальные стили и без index.css

**Comment by Uladzislau-Rahinia** [comment]
> Какой смысл выносить в общий компонент TextInput если он всего-лишь обёрнут в styled и никакой общей логики нет

Он используется на 3 страницах (логин, регистрация, создание таски) и чтобы не копипастить стили в каждую страницу я его и вынес

> Компоненты которые ориентированные только на одну страницу и нигде более использовать не будут лучше всего не выносить в общую папку components, а добавить новую папку для компонента components

Я вот тут немного не понял. Типа, где эту папку создать? В папке соответствующей страницы и в нее кинуть папку с компонентом? (пример как я понял: HomePage/components/TaskList/)

Еще вопрос по поводу линтера, он в propTypes ругается на типы object и array, и если статические объекты можно задать через shape, то вот у меня объекты со сгенерированными динамическими ключами, и мне не понятно как с ними можно поступить

И последний вопрос про useCallback, я убрал его с инлайн функций, но мне непонятно где его **именно в моем случае** можно использовать и какие методы мемоизировать, на методе генерации календаря уже есть useMemo, а кроме него я не знаю что еще имело бы смысл мемоизировать, так как большинство коллбэков - инлайн методы в одну строку

Все остальное я исправил

**Comment by bitvalser** [comment]
> Он используется на 3 страницах (логин, регистрация, создание таски) и чтобы не копипастить стили в каждую страницу я его и вынес

В этом случае я бы вынес именно styled компонент отдельно тогда, нормальная тема выносить общие стили, всегда стоит думать как уменьшить кол-во повторяющегося кода и как сделать компонент более реиспользуемым, но обрати внимание именно в этом случае лучше вынести styled, так как если бы у тебя была какая-либо общая логика, то вполне можно было бы так и оставить

> Я вот тут немного не понял. Типа, где эту папку создать? В папке соответствующей страницы и в нее кинуть папку с компонентом? (пример как я понял: HomePage/components/TaskList/)

Да именно так

> Еще вопрос по поводу линтера, он в propTypes ругается на типы object и array, и если статические объекты можно задать через shape, то вот у меня объекты со сгенерированными динамическими ключами, и мне не понятно как с ними можно поступить

Это правило линтера (на object и array) можно пока отключить, не критично

> И последний вопрос про useCallback, я убрал его с инлайн функций, но мне непонятно где его именно в моем случае можно использовать и какие методы мемоизировать, на методе генерации календаря уже есть useMemo, а кроме него я не знаю что еще имело бы смысл мемоизировать, так как большинство коллбэков - инлайн методы в одну строку

Почитай статью: https://kentcdodds.com/blog/usememo-and-usecallback

**Comment by Uladzislau-Rahinia** [comment]
Исправил
